### PR TITLE
Remove unused bad json file

### PR DESCRIPTION
**Pull request by alextes**
`flow` got upset there was an (intentionally) bad JSON file somewhere in the test dir. Not sure why it picks up the one I removed, `ja.json`, but not the `_malformed.json` somewhere in your deps.

In any case, the file appears unused, this seems like a fine solution. I can imagine an alternative would be creating a flow def over at [flow-typed](https://github.com/flowtype/flow-typed) for this project that does nothing but tells flow to ignore the bad file.

### CODE REVIEW

**Comment by martinheidegger** [comment]
Yes, the ja.json seems like a left-over. Thank you for pointing me towards it.

**Comment by martinheidegger** [comment]
😊 I completely forgot where I used the bad json file! Its part of a test to see how i18n reacts to a broken js.

**Comment by martinheidegger** [comment]
https://travis-ci.org/martinheidegger/i18n-core/builds/237020228

**Comment by alextes** [comment]
I'm still very confused @martinheidegger 😅.
The build you linked talks about two failing tests, but I only see one failing, and that seems a fluke.
So where is the second failing test? Is it the relevant one? 
Why is mustacheSimple failing? It passes for me locally without the file. Fluke, or was that what you wanted to point at?
I understand you want to test i18n reacting to bad JSON but there seems to be no test that does it. I looked the CI build, `test/lookup/fs.js` three times. `lookup/fs.js` doesn't seem to eagerly read or anything either. Is there a test somewhere that reads the whole folder? I get the feeling there is code somewhere that reads the full folder.

Maybe after you explain why `ja.json` needs to exist we can add a comment to `test/lookup/fs.js`, `test/basic.js` or whichever test you'd expect to possibly break on bad JSON?

**Comment by martinheidegger** [comment]
:sweat_smile: I am a hot mess these days :cold_sweat:. I saw the broken test and I panicked...
Would you mind to un-remove the `remove-ja-json` branch so I can merge it once more :bow:

**Comment by alextes** [comment]
@martinheidegger haha, don't worry about it. You're a contributive hot mess. I see you do lots around the ecosystem.

And done 😁 !

**Comment by martinheidegger** [comment]
Thanks, I just published 3.1.4 that has this and a few other improvements.

**Pull request merged**
